---
title: "Host letter"
output: html_document
date: "2026-01-15"
---

[Institution Letterhead]
Date: [Insert Date]

To Whom It May Concern,

Subject: Hosting Confirmation for the Project “Metabolic Signatures in Pre-Diabetes: Decoding Incretin and Glucagon Pathways and Their Interaction with Metabolic Traits in Cardiometabolic Disease Progression”

I hereby confirm that [Host Institution Name] will host the above-mentioned project led by [Main Applicant Name] as part of the Inter-SUSTAIN initiative.

The institution agrees to the following:
1. Project Hosting and Infrastructure\
The project will take place at [Host Institution Name], which will provide the necessary infrastructure, including laboratory and office space, as well as administrative support for the management of the grant. \
2. Budget Agreement and Grant Administration\
The institution has reviewed and agreed to the submitted budget and will manage any potential grant in accordance with this budget and institutional financial policies.\
3. Terms of Employment\
The main applicant’s employment at [Host Institution Name] is secured for the duration of the project. Funding for the main applicant’s salary is guaranteed under existing institutional arrangements.\

We look forward to supporting this important research, which aims to elucidate the role of natural incretin and glucagon responses in the progression of pre-diabetes and related cardiometabolic complications, leveraging data from the Fenland Study, ADDITION-PRO, and UK Biobank.\

Should you require any further information, please do not hesitate to contact us.\

Sincerely,\
Michael Baggesen Klitgaard\
Head of Department\
Department of Public Health, Aarhus University